FROM centos:7

MAINTAINER Pahud Hsieh <pahudnet@gmail.com>

# repo info:  https://copr.fedorainfracloud.org/coprs/openresty/openresty/
# official RPM packages:  http://openresty.org/en/rpm-packages.html

RUN yum-config-manager --add-repo https://copr.fedorainfracloud.org/coprs/openresty/openresty/repo/epel-7/openresty-openresty-epel-7.repo && \
yum install -y openresty

ADD ./start.centos7.sh /root/

EXPOSE 80

CMD ["/root/start.centos7.sh"]
